const GET_BOOKS_BEGIN = 'GET_BOOKS_BEGIN';
const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';

const GET_SINGLE_BOOK_BEGIN = 'GET_SINGLE_BOOK_BEGIN';
const GET_SINGLE_BOOK_SUCCESS = 'GET_SINGLE_BOOK_SUCCESS';
const GET_SINGLE_BOOK_ERROR = 'GET_SINGLE_BOOK_ERROR';

const UPDATE_WAITINGLIST_BEGIN = 'UPDATE_WAITINGLIST_BEGIN';
const UPDATE_WAITINGLIST_SUCCESS = 'UPDATE_WAITINGLIST_SUCCESS';
const UPDATE_WAITINGLIST_ERROR = 'UPDATE_WAITINGLIST_ERROR';

const CREATE_RESERVATION_SUCCESS = 'CREATE_RESERVATION_SUCCESS';

const UPDATE_STATUS = 'UPDATE_STATUS';

const GET_RESERVATION_ERROR = 'GET_RESERVATION_ERROR';
const CREATE_RESERVATION_ERROR = 'CREATE_RESERVATION_ERROR';

const CLEAR_ALERT = 'CLEAR_ALERT';

export {
  GET_BOOKS_BEGIN,
  GET_BOOKS_SUCCESS,
  GET_BOOKS_ERROR,
  GET_SINGLE_BOOK_BEGIN,
  GET_SINGLE_BOOK_SUCCESS,
  GET_SINGLE_BOOK_ERROR,
  UPDATE_WAITINGLIST_BEGIN,
  UPDATE_WAITINGLIST_SUCCESS,
  UPDATE_WAITINGLIST_ERROR,
  UPDATE_STATUS,
  CREATE_RESERVATION_SUCCESS,
  GET_RESERVATION_ERROR,
  CREATE_RESERVATION_ERROR,
  CLEAR_ALERT,
};
