const GET_BOOKS_BEGIN = 'GET_BOOKS_BEGIN';
const GET_BOOKS_SUCCESS = 'GET_BOOKS_SUCCESS';
const GET_BOOKS_ERROR = 'GET_BOOKS_ERROR';

const GET_SINGLE_BOOK_BEGIN = 'GET_SINGLE_BOOK_BEGIN';
const GET_SINGLE_BOOK_SUCCESS = 'GET_SINGLE_BOOK_SUCCESS';
const GET_SINGLE_BOOK_ERROR = 'GET_SINGLE_BOOK_ERROR';

export {
  GET_BOOKS_BEGIN,
  GET_BOOKS_SUCCESS,
  GET_BOOKS_ERROR,
  GET_SINGLE_BOOK_BEGIN,
  GET_SINGLE_BOOK_SUCCESS,
  GET_SINGLE_BOOK_ERROR,
};
