const LOAD_BOOKS = 'LOAD_BOOKS';
const UPDATE_SORT = 'UPDATE_SORT';

const CLEAR_FILTERS = 'CLEAR_FILTERS';
const SORT_BOOKS = 'SORT_BOOKS';
const UPDATE_FILTERS = 'UPDATE_FILTERS';
const FILTER_BOOKS = 'FILTER_BOOKS';

export {
  LOAD_BOOKS,
  UPDATE_SORT,
  SORT_BOOKS,
  UPDATE_FILTERS,
  FILTER_BOOKS,
  CLEAR_FILTERS,
};
