const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';

const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

const LOGOUT_USER = 'LOGOUT_USER';

const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN';
const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
const UPDATE_USER_ERROR = 'UPDATE_USER_BEGIN';

const CLEAR_ALERT = 'CLEAR_ALERT';

const SHOW_CUSTOM_ALERT = 'SHOW_CUSTOM_ALERT';

const UPDATE_RESERVE_BEGIN = 'UPDATE_RESERVE_BEGIN';
const UPDATE_RESERVE_SUCCESS = 'UPDATE_RESERVE_SUCCESS';
const UPDATE_RESERVE_ERROR = 'UPDATE_RESERVE_ERROR';

const PROCESS_BEGIN = 'PROCESS_BEGIN';

const GET_RESERVATIONS_SUCCESS = 'GET_RESERVATIONS_SUCCESS';
const GET_RESERVATIONS_ERROR = 'GET_RESERVATIONS_ERROR';

export {
  REGISTER_USER_BEGIN,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  LOGOUT_USER,
  UPDATE_USER_BEGIN,
  UPDATE_USER_SUCCESS,
  UPDATE_USER_ERROR,
  CLEAR_ALERT,
  SHOW_CUSTOM_ALERT,
  UPDATE_RESERVE_BEGIN,
  UPDATE_RESERVE_SUCCESS,
  UPDATE_RESERVE_ERROR,
  PROCESS_BEGIN,
  GET_RESERVATIONS_SUCCESS,
  GET_RESERVATIONS_ERROR,
};
